name: surgeon_control_panel
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.0
  flutter_vlc_player: ^7.4.3
  flutter_mjpeg: ^2.0.4
  flutter_webrtc: ^0.14.1
  youtube_player_flutter: ^9.1.1
  get: ^4.7.2
  connectivity_plus: ^6.1.4
  another_flutter_splash_screen: ^1.2.1
  neopop: ^1.0.2
  animated_button: ^0.3.1
  share_plus: ^11.0.0
  flutter_in_app_pip: ^1.7.4
  stop_watch_timer: ^3.2.2
  syncfusion_flutter_gauges: ^30.1.37
  analog_clock: ^0.1.1
  just_audio: ^0.10.4
  audio_session: ^0.2.2
  google_fonts: ^4.0.4
  material_design_icons_flutter: ^7.0.7296
  one_clock: ^2.0.1
  http: ^0.13.6
  web_socket_channel: ^3.0.3
  provider: ^6.1.5
  video_player: ^2.9.5
  flutter_colorpicker: ^1.1.0
  usb_serial: ^0.5.2
  permission_handler: ^12.0.1
  screenshot: ^3.0.0
  flutter_localization: ^0.3.3
  intl: ^0.20.2
  fluttertoast: ^8.2.12
  path: ^1.9.1
  file_picker: ^10.3.1
  flutter_screen_recording: ^2.0.24
  percent_indicator: ^4.2.5
  fl_chart: ^0.69.0
  android_intent_plus: ^5.3.1
  url_launcher: ^6.3.2
  audioplayers: ^6.5.1
  camera: ^0.11.2
  image_picker: ^1.2.0
  slide_digital_clock: ^1.0.3
  gif_view: ^0.3.1
  chewie: ^1.13.0
  file_saver: ^0.3.1
  open_filex: ^4.7.0
  photo_view: ^0.15.0
  flutter_pdfview: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  image_path: "assets/icon/icon.jpeg"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/app_logo-removebg-preview.png
    - assets/wiespl_indro.mp4
    - assets/la/ar.json
    - assets/la/hi.json
    - assets/la/en.json
    - assets/bgi.jpg
    - assets/Download Human Heart Anatomy for free.jpg
    - assets/icon/icon.jpeg
    - assets/audio/AirBar3.mp3
    - assets/audio/AirBar7.mp3
    - assets/audio/CO2.mp3
    - assets/audio/Nitrogen.mp3
    - assets/audio/Oxygen.mp3
    - assets/audio/VaccumError.mp3
    - assets/audio/NormalAir.mp3
    - assets/image.png
    - assets/marcel-scholte-LPurJnihmQI-unsplash.jpg
    - assets/irwan-rbDE93-0hHs-unsplash.jpg
    - assets/music/Gayatri Mantra_128-(PagalWorld.Org.Im).mp3
    - assets/music/He Ram He Ram-320kbps.mp3
    - assets/music/Mahamrityunjay Mantra महमतयजय मतर Om Trayambakam Yajamahe.mp3
    - assets/music/Shiv Namaskarartha Mantra  Monday Special  LoFi Version.mp3
    - assets/music/Sri Venkatesha Stotram - Invoking the Lord's Mercy _ New Year 2025.mp3
    - assets/music/Sri Venkateshwara Suprabhatham-320kbps.mp3
    - assets/music/शर हनमन चलस  Shree Hanuman Chalisa Original Video  GULSHAN KUMAR  HARIHARAN Full HD.mp3
